version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'tabinary-storage'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'tabi'
      MYSQL_ROOT_PASSWORD: 'tabi'
    ports:
      - '3305:3305'
    expose:
      - '3305'
    volumes:
      - tabinary-storage:/var/lib/mysql
volumes:
  tabinary-storage: